version: '3.8'

services:
  app:
    build: .
    container_name: container-comp-vision-table-parser
    image: comp-vision-table-parser:latest
    volumes:
      - ./input_images:/app/input_images
      - ./test_data:/app/test_data
      - ./output_finish:/app/output_finish
      - .:/app/raw_dir